# Generated by Django 5.1.1 on 2024-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
